-- Tea Leaves menu schema
-- Apply in Supabase SQL Editor or via: supabase db push

create table if not exists public.categories (
  id text primary key,
  emoji text not null default '📦',
  image_url text,
  label_en text not null,
  label_ar text not null default '',
  label_ku text not null default '',
  sort_order integer not null default 0
);

create table if not exists public.menu_items (
  id bigint generated by default as identity primary key,
  category_id text not null references public.categories (id) on delete cascade,
  name_en text not null,
  name_ar text not null default '',
  name_ku text not null default '',
  ing_en text,
  ing_ar text,
  ing_ku text,
  price integer not null check (price >= 0),
  photo_url text,
  tags text[] not null default '{}',
  is_available boolean not null default true,
  created_at timestamptz not null default now()
);

create index if not exists menu_items_category_id_idx on public.menu_items (category_id);
create index if not exists menu_items_is_available_idx on public.menu_items (is_available);
